logging:
  level: INFO

  # Logger-specific levels.
  loggers:
    com.ycourtois.rankingparadise: INFO

  appenders:
    - type: console

server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

dynamodb:
  aws:
    profile: ${AWS_PROFILE:-'default'}
    region: ${AWS_REGION:-'eu-west-1'}
    endpoint: ${AWS_ENDPOINT:-}
    #endpoint: 'http://localhost:4566' # localstack
  table: "players"
  primaryKey: "nickname"
  gsi: "score_index"